server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${OFBIZ_JDBC_URL:jdbc:postgresql://localhost:5432/ofbizmaindb}
    username: ${OFBIZ_DB_USER:ofbiz}
    password: ${OFBIZ_DB_PASSWORD:ofbiz}
  jackson:
    default-property-inclusion: non_null
